### GET ALL
GET https://fiestaappapi.onrender.com/api/djs/opiniones

### GET ALL
http://localhost:3000/api/djs/654486d2b4a6caa365177ad2/opiniones

### POST
POST https://fiestaappapi.onrender.com/api/djs
Content-Type: application/json

{
    "nombre": "valen",
    "instagram": "as",
    "tel":2457,
    "actual":false
}


### GET ONE
GET https://fiestaappapi.onrender.com/api/djs/654443d6ac72c35a43ed17da


### PUT
PUT  https://fiestaappapi.onrender.com/api/djs/654486e3b4a6caa365177ad3
Content-Type: application/json

{
    "actual":false
}

### PUT
PUT http://localhost:3000/api/djs/6545400c3b2ca1bfec740ca8
Content-Type: application/json

{
    "actual":true
}

### PUT
PUT http://localhost:3000/api/djs/6545400c3b2ca1bfec740ca8
Content-Type: application/json

{
    "actual":true
}

### PUT
PUT http://localhost:3000/api/djs/actual/65454eb37c19b455a57835e1
Content-Type: application/json

{
    "actual":true
}

### DELETE
DELETE https://fiestaappapi.onrender.com/api/djs/654443d6ac72c35a43ed17da
