### GET ALL
GET https://fiestaappapi.onrender.com/api/djs

### GET ALL
http://localhost:3000/api/djs

### POST
POST http://localhost:3000/api/djs
Content-Type: application/json

{
    "nombre": "prueba1 DJ",
    "instagram": "pdj",
    "tel":4521,
    "actual":false
}

### POST
POST https://fiestaappapi.onrender.com/api/djs
Content-Type: application/json

{
    "nombre": "prueba2 DJ",
    "instagram": "pddj",
    "tel":251,
    "actual":false
}

### GET ONE
GET https://fiestaappapi.onrender.com/api/djs/66184337220f869092e27e72


### PUT
PUT  https://fiestaappapi.onrender.com/api/djs/654486e3b4a6caa365177ad3
Content-Type: application/json

{
    "actual":false
}

### PUT
PUT http://localhost:3000/api/djs/6545400c3b2ca1bfec740ca8
Content-Type: application/json

{
    "actual":true
}

### PUT
PUT http://localhost:3000/api/djs/6545400c3b2ca1bfec740ca8
Content-Type: application/json

{
    "actual":true
}

### PUT
PUT http://localhost:3000/api/djs/actual/65454eb37c19b455a57835e1
Content-Type: application/json

{
    "actual":true
}

### DELETE
DELETE https://fiestaappapi.onrender.com/api/djs/654e8fa609380ce52a840c77

### DELETE
DELETE http://localhost:3000/api/djs/654e8fa609380ce52a840c77

### GET ALL
http://localhost:3000/api/djs/opiniones


### POST
POST http://localhost:3000/api/djs/opinion
Content-Type: application/json

{
    "opinion": "Es muy bueno"
}

### GET ONE
GET http://localhost:3000/api/djs/65458887db3542c3e0703d34/opinion
// 654486d2b4a6caa365177ad2

### GET ONE
GET http://localhost:3000/api/djs/654486d2b4a6caa365177ad2/opiniones


### GET ONE
GET http://localhost:3000/api/djs/66184337220f869092e27e72




### GET UPDATE ACTUAL
GET http://localhost:3000/api/djs/fechanueva


### GET ACTUAL
GET http://localhost:3000/api/djs/actual