### GET ALL
GET https://fiestaappapi.onrender.com/api/

### POST
POST http://localhost:3000/api/canciones
Content-Type: application/json
{
    "nombre": "lala",
    "autor": "myke",
}


### GET ONE
GET https://fiestaappapi.onrender.com/api/djs/654443d6ac72c35a43ed17da


### PUT
PUT  https://fiestaappapi.onrender.com/api/djs/654448f8414bbd614739725e
Content-Type: application/json

{
    "nombre": "juanii",
    "instagram": "ii22",
    "tel":416,
    "actual":true
}

### DELETE
DELETE https://fiestaappapi.onrender.com/api/djs/654443d6ac72c35a43ed17da
