### GET ALL
GET https://fiestaappapi.onrender.com/api/canciones

### GET ALL
GET http://localhost:3000/api/canciones/

### POST
POST https://fiestaappapi.onrender.com/api/canciones
Content-Type: application/json

{
    "nombre": "fea",
    "autor": "ozuna",
}

### POST
POST http://localhost:3000/api/canciones/
Content-Type: application/json

{
  "nombre": "fea",
  "autor":"ozuna"
}

### GET ONE
GET https://fiestaappapi.onrender.com/api/canciones/654542d78f45a8c9b68c6cd7


### PUT
PUT  https://fiestaappapi.onrender.com/api/canciones/654542d78f45a8c9b68c6cd7
Content-Type: application/json

{
    "nombre": "Myke",
    "autor": "LALA"
}

### PUT
PUT http://localhost:3000/api/canciones/654542d78f45a8c9b68c6cd7
Content-Type: application/json

{
    "nombre": "Mykee",
    "autor": "LALAA"
}

### DELETE
DELETE https://fiestaappapi.onrender.com/api/canciones/654542e18f45a8c9b68c6cd8
